FROM debian:stretch

RUN apt-get update -y
RUN apt-get install -y git make gcc libtool zlib1g-dev openssl patch vim-common libluajit-5.1-dev pkg-config autoconf libssl-dev

WORKDIR /opt/logd
VOLUME /opt/logd/bin

COPY . /opt/logd

RUN ./configure --enable-build-libuv CFLAGS='-I/opt/logd/deps/include -I/usr/include/luajit-2.0 -DOPENSSL_NO_STDIO -O3'

CMD make
