FROM alpine:3.7

RUN apk update && apk add alpine-sdk coreutils libtool automake m4 autoconf linux-headers vim sed

WORKDIR /opt/logd
VOLUME /opt/logd/bin

COPY . /opt/logd

RUN ./configure LDFLAGS='-static -L/opt/logd/deps/lib' CFLAGS='-I/opt/logd/deps/include -I/opt/logd/deps/include/luajit-2.0 -O3' --enable-build-all

CMD make
