FROM centos:7

RUN yum install -y epel-release && yum update -y
RUN yum install -y git make gcc libtool zlib-devel openssl-devel patch vim-common

WORKDIR /opt/logd
VOLUME /opt/logd/bin

COPY . /opt/logd

RUN ./configure CFLAGS='-DOPENSSL_NO_SRP -I/opt/logd/deps/include -I/opt/logd/deps/include/luajit-2.0 -O3' --enable-build-luajit --enable-build-libuv

CMD make
